steps:
  - name: "hashicorp/terraform"
    id: terraform-deploy-plan
    script: |
      terraform -chdir=infra/terraform/deploy/environments/${ENVIRONMENT} init -backend-config=bucket=$TFSTATE_BUCKET

      terraform -chdir=infra/terraform/deploy/environments/${ENVIRONMENT} plan -lock-timeout=60m
    env:
      - "TFSTATE_BUCKET=${_TFSTATE_BUCKET}"
      - "ENVIRONMENT=${_ENVIRONMENT}"
      - "TF_VAR_project_id=${PROJECT_ID}"
options:
  logging: CLOUD_LOGGING_ONLY
