steps:
  - name: "hashicorp/terraform"
    id: terraform-networking-plan
    dir: infra/terraform/networking
    script: |
      terraform init -backend-config=bucket=$TFSTATE_BUCKET

      terraform plan
    env:
      - "TFSTATE_BUCKET=${_TFSTATE_BUCKET}"
      - "TF_VAR_naming_convention_environment_code=${_NAMING_CONVENTION_ENVIRONMENT_CODE}"
      - "TF_VAR_naming_convention_prefix=${_NAMING_CONVENTION_PREFIX}"
      - "TF_VAR_naming_convention_suffix=${_NAMING_CONVENTION_SUFFIX}"
      - "TF_VAR_naming_convention_project=${_NAMING_CONVENTION_PROJECT}"
      - "TF_VAR_project_id=${PROJECT_ID}"
options:
  logging: CLOUD_LOGGING_ONLY
